### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by Sunekaer** [drizzs/GrassWorld-1.14#1]
Client-side stuff trying to load on server.
https://paste.dimdev.org/exubiqicos.sql

**Comment by drizzs** [comment]
Yeah Sorry about that, i thought i had fixed that which is why i updated in the first place. I'll fix this today!

**Comment by drizzs** [comment]
Pretty sure this new update will fix this issue! Thanks for bringing it to my attention it was really my fault in the first place. Sorry about that I thought i had cleared up my code but i missed something!

**Comment by drizzs** [comment]
Update Released, I tested it, should work if not I'll leave this open for any reply if you don't reply in 7 days I'll assume it works and close it! Thanks!
