### ISSUE TITLE
Several Seeds are Missing Localization

### ISSUE THREAD

**Issue by WenXin20** [drizzs/GrassWorld-1.14#5]
`Mineceaft v1.14.4`
`Forge v28.1.104`
`Grass World v2.0.0`

All Glowing Seeds, Lime Seeds, Gray Seeds, Light Gray Seeds, Light Blue Seeds and their corresponding blocks are missing localization.

**Comment by drizzs** [comment]
As in missing the correct names? yeah the thing with those is that because i changed the system completely it messed up how i named everything. So i'll have this resolved in the next update! Which will be very soon i'll probably do this before the weekend is over!

**Comment by WenXin20** [comment]
Yep, they display `item.grassworld.light_blueseed`

**Comment by drizzs** [comment]
Already Fixed
